version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8001:80
      - 4431:443
    links:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    volumes_from:
      - php:ro
  php:
    build: docker/php
    links:
      - mysql:mysql
      - cache:rediscache
      - sessions:redissession
      #- fullpagecache:redisfullpagecache
      #- solr:solr
    volumes:
      - ./public:/var/www/html
  mysql:
    image: mysql:5.7.12
    environment:
      MYSQL_DATABASE: project
      MYSQL_USER: magento
      MYSQL_PASSWORD: h78049hgr789fjpw3f7h8hyh8y4f
      MYSQL_ROOT_PASSWORD: yg789u0ijhvtr678ygtr678yh6f8787
    command: "/run/run.sh" # remove if you dont want to mount db data
    volumes:
      - ./data/db/mysql:/var/lib/mysql:rw # remove if you dont want to mount db data
      - ./docker/db/run.sh:/run/run.sh:rw # remove if you dont want to mount db data
  cache:
    image: redis:latest
  sessions:
    image: redis:latest
  #fullpagecache:
  #  image: redis:latest
  #solr:
  #  build: docker/solr